name: CICD
on: push

jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
    - name: Run many tests
      run: echo "build job"

  test_job:
    needs: build_job
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: echo "Running tests"

  deploy_job:
    needs: test_job
    runs-on: ubuntu-latest
    steps:
      - name: Deploy 
        run: echo "Deploying"|
        